### ISSUE TITLE
User Database Integrity Check jobs fail on secondary AG servers

### ISSUE THREAD

**Issue by Brianc-DBA** [olahallengren/sql-server-maintenance-solution#320]
**Description of the issue**
Starting with the 20200102 release, and behaving the same in the 20200106 release, the user integrity check jobs on all our Availability Groups' secondary servers fail.  Until this release the jobs were running for years without issues on the secondaries.  The secondary servers have 1-3 local databases, but none of the synchronized databases (such as AGTest) are readable on the secondary.  I am not certain why the job now tries to run against the synchronized databases from the secondaries.

**SQL Server version and edition**
Tested on SQL 2016 and 2012
Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64)   Nov 27 2019 18:09:22   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64)   Feb 28 2018 17:47:20   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

**Version of the script**
20200106

**What command are you executing?**
sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d DBA -Q "EXECUTE [dbo].[DatabaseIntegrityCheck] @Databases = 'USER_DATABASES', @LogToTable = 'Y'" -b
**What output are you getting?**
-- 2016:
Executed as user: APACORP\svcsql. Date and time: 2020-01-06 10:03:35  Server: INF-SQLP203  Version: 13.0.5598.27  Edition: Enterprise Edition: Core-based Licensing (64-bit)  Platform: Windows  Procedure: [DBA].[dbo].[DatabaseIntegrityCheck]  Parameters: @Databases = 'USER_DATABASES', @CheckCommands = 'CHECKDB', @PhysicalOnly = 'N', @NoIndex = 'N', @ExtendedLogicalChecks = 'N', @TabLock = 'N', @FileGroups = NULL, @Objects = NULL, @MaxDOP = NULL, @AvailabilityGroups = NULL, @AvailabilityGroupReplicas = 'ALL', @Updateability = 'ALL', @TimeLimit = NULL, @LockTimeout = NULL, @LockMessageSeverity = 16, @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'  Version: 2020-01-02 20:43:38  Source: https://ola.hallengren.com  	  Date and time: 2020-01-06 10:03:35  Database: [AGTest]  State: ONLINE  Standby: No  Updateability: READ_WRITE  User access: MULTI_USER  Is accessible: Yes  Recovery model: FULL  Availability group: PRODBI-AG  Availability group role: SECONDARY  	  Date and time: 2020-01-06 10:03:35  Database context: [AGTest]  Command: DBCC CHECKDB ([AGTest]) WITH NO_INFOMSGS, ALL_ERRORMSGS, DATA_PURITY  Msg 976, Level 14, State 1, Server INF-SQLP203, Procedure CommandExecute, Line 206  The target database, 'AGTest', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.  Process Exit Code 1.  The step failed.

-- 2012:
Executed as user: APACORP\svcsql. Date and time: 2020-01-06 10:02:36  Server: APP-SRV50  Version: 11.0.7469.6  Edition: Enterprise Edition (64-bit)  Platform: Windows  Procedure: [DBA].[dbo].[DatabaseIntegrityCheck]  Parameters: @Databases = 'USER_DATABASES', @CheckCommands = 'CHECKDB', @PhysicalOnly = 'N', @NoIndex = 'N', @ExtendedLogicalChecks = 'N', @TabLock = 'N', @FileGroups = NULL, @Objects = NULL, @MaxDOP = NULL, @AvailabilityGroups = NULL, @AvailabilityGroupReplicas = 'ALL', @Updateability = 'ALL', @TimeLimit = NULL, @LockTimeout = NULL, @LockMessageSeverity = 16, @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'  Version: 2020-01-02 20:43:38  Source: https://ola.hallengren.com  	  Date and time: 2020-01-06 10:02:37  Database: [AGTest]  State: ONLINE  Standby: No  Updateability: READ_WRITE  User access: MULTI_USER  Is accessible: Yes  Recovery model: FULL  Availability group: MNTDW-AG  Availability group role: SECONDARY  	  Date and time: 2020-01-06 10:02:37  Database context: [AGTest]  Command: DBCC CHECKDB ([AGTest]) WITH NO_INFOMSGS, ALL_ERRORMSGS, DATA_PURITY  Msg 978, Level 14, State 1, Server APP-SRV50, Procedure CommandExecute, Line 206  The target database ('AGTest') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.  Process Exit Code 1.  The step failed.

**Comment by olahallengren** [comment]
@Brianc-DBA, I am sorry about this issue. I am looking into it now.

**Comment by olahallengren** [comment]
I have released a fix for this. Thank you for reporting this issue.

**Comment by Brianc-DBA** [comment]
Thanks for the fast response.  The new version seems to have fixed the issue.  The script still checks the synchronized databases from the secondary, but no longer fails.

**Comment by olahallengren** [comment]
This sounds very good. Thank you for reporting back.

**Comment by shaikaijaz** [comment]
Getting this issue on the below server version after latest Windows updates were installed. Was working fine before. Have deployed latest scripts but still the same issue. DatabaseIntegrityCheck is failing on the secondary server with the below error..

Error:
Msg 976, Level 14, State 1, Line 3
The target database, '*', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

SQL version:
Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64)   Jan 23 2020 21:00:04   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by shaikaijaz** [comment]
@olahallengren 

Getting this issue on the below server version after latest Windows updates were installed. Was working fine before. Have deployed latest scripts but still the same issue. DatabaseIntegrityCheck is failing on the secondary server with the below error..

Error:
Msg 976, Level 14, State 1, Line 3
The target database, '*', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

SQL version:
Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64)   Jan 23 2020 21:00:04   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)
