### ISSUE TITLE
IndexOptimize Delay Gives Error

### ISSUE THREAD

**Issue by imyourdba** [olahallengren/sql-server-maintenance-solution#340]
We just updated our dbo.IndexOptimize today (Version: 2020-01-14 21:48:14).

We are using @Delay =1 in the IndexOptimize execution statement and are now getting the following error, but the process does continue on.
_Msg 9815, Level 16, State 0, Procedure master.dbo.IndexOptimize, Line 2160 [Batch Start Line 0]
Waitfor delay and waitfor time cannot be of type datetime2._

Date and time: 2020-01-25 13:45:37
Server: {removed}
Version: 14.0.3208.1
Edition: Enterprise Edition: Core-based Licensing (64-bit)
Platform: Windows
Procedure: [master].[dbo].[IndexOptimize]
Parameters: @Databases = '{Removed}', @FragmentationLow = NULL, @FragmentationMedium = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE', @FragmentationLevel1 = 10, @FragmentationLevel2 = 30, @MinNumberOfPages = 1, @MaxNumberOfPages = NULL, @SortInTempdb = 'N', @MaxDOP = 1, @FillFactor = 80, @PadIndex = NULL, @LOBCompaction = 'Y', @UpdateStatistics = NULL, @OnlyModifiedStatistics = 'N', @StatisticsModificationLevel = NULL, @StatisticsSample = NULL, @StatisticsResample = 'N', @PartitionLevel = 'Y', @MSShippedObjects = 'N', @Indexes = 'ALL_INDEXES, -{Removed}.BAK.%', @TimeLimit = NULL, @Delay = 1, @WaitAtLowPriorityMaxDuration = NULL, @WaitAtLowPriorityAbortAfterWait = NULL, @Resumable = 'N', @AvailabilityGroups = NULL, @LockTimeout = NULL, @LockMessageSeverity = 16, @StringDelimiter = ',', @DatabaseOrder = NULL, @DatabasesInParallel = 'N', @LogToTable = 'Y', @Execute = 'Y'
Version: 2020-01-14 21:48:14
Source: https://ola.hallengren.com

**Comment by marcoincalcaterra** [comment]
I have the same problem on Azure SQL:

Version: 12.0.2000.8
Edition: SQL Azure
Platform: Windows

**Comment by olahallengren** [comment]
This issue has been fixed. Thank you for reporting it.

**Comment by S-Coutant** [comment]
Not fixed...

**Comment by imyourdba** [comment]
It’s fixed for me. Did you download the file from Github?

Sincerely,

Jacob Golden
Principal SQL DBA
M: 913-486-8328

On Jan 27, 2020, at 7:55 AM, S-Coutant <notifications@github.com> wrote:

﻿

Not fixed...

**Comment by S-Coutant** [comment]
Duhhhhh, I redownloaded the script this morning, but was looking at Job output from before I re-downloaded.  Sorry about the confusion.
